teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.4

    require_enable_button: true
    enable_button: 4  # TL shoulder button
    enable_turbo_button: -1  # disabled
